Temporary fix: Do not check version conflict
It some times was producing the following during start:

...
Adding missing node: xapiand-server-10
Exception: DocVersionConflictError: Version mismatch!